### ISSUE TITLE
Build, package then share your Angular Library across applications

### ISSUE THREAD

**Issue by chihab** [ngMorocco/meetup-call-for-proposals#1]
## Format
Long (=~ 20mn)

## Description
If you want to share a Angular module across multiple applications, you have to extract, package and distribute it accordingly. Angular 6 has made this process really easy. One who has ever tried to do it before knows that it was not that simple.

In this talk we will first describe the building/packaging challenges then explain how Angular 6 has made it handy. For that, we are going to create a library that provides a service, some components, we'll publish it on npm and then use it as a dependency in a newly created application.

Slides : https://slides.com/chihab/ngmorocco-build-share-lib/fullscreen
Source code : https://github.com/chihab/ngx-library-di

**Comment by ouadie-lahdioui** [comment]
Well done.

Thank you @chihab
