### ISSUE TITLE
[Live Coding] - Advanced Angular Component Patterns

### ISSUE THREAD

**Issue by chihab** [ngMorocco/meetup-call-for-proposals#5]
## Format
Live coding (=~ 30mn)

## Description
In this talk we’ll see how it is possible to move an Angular component from completely static to very configurable (state and view) using inputs, content projection and template references.

- Basic inputs and ouptuts between parent and child components
- Write compound components using content projection
- Share parent component state using dependency injection
- React's Render Prop pattern using template references

No advanced skills required, you'd need to know the basics of creating Angular components, use inputs and outputs.

Source code: https://github.com/chihab/angular-advanced-components
Demo: https://sad-lichterman-b6aa41.netlify.com

**Comment by ouadie-lahdioui** [comment]
Awesome !

Thank u @chihab for the proposal

**Comment by ouadie-lahdioui** [comment]
Done.
