### ISSUE TITLE
Angular Reactive Forms

### ISSUE THREAD

**Issue by chihab** [ngMorocco/meetup-call-for-proposals#6]
## Basics of Angular Reactive Forms (45mn)
Template-driven forms offer directives that handle data binding and form validation. These directives directly applied to input/forms in component templates are the default and most common way to work with forms in Angular. 
Reactive Forms, while a little be complex at the beginning makes easy to build your own representation of a form in the component class, create forms dynamically from a data set, build you own custom validators... 

## Build an Instant Search Component using Reactive Forms and RxJS (45mn)
We will leverage the power Angular's Reactive Forms and RxJS observables/operators to build an instant search component

**Comment by ouadie-lahdioui** [comment]
Presented by @chihab in monthly august meetup

Thank you again
